name: CI

on:
  push:
    branches: [main, dev, feature/sgd, feature/momentum_decay, feature/adam]
  pull_request:
    branches: [main, dev]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-13]

    steps:
      - uses: actions/checkout@v3

      - name: Install GCC 13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install gcc-13 g++-13 -y

      - name: Build
        run: make -C COMP36212_EX3_Code CC=gcc-13 CFLAGS="-O3 -Wall -Werror"

      - name: Unit-tests (C)
        run: make -C COMP36212_EX3_Code test

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy matplotlib

      - name: Gradcheck
        run: make -C COMP36212_EX3_Code gradcheck || true

      - name: Plot scripts
        run: make -C COMP36212_EX3_Code plot

      - name: SGD baseline
        run: ./COMP36212_EX3_Code/mnist_optimiser.out mnist_data 0.1 0.1 10 1 0 0.0 0.0 1e-8

      - name: Momentum test
        run: ./COMP36212_EX3_Code/mnist_optimiser.out mnist_data 0.01 0.0001 10 1 1 0.9 0.0 1e-8

      - name: Adam test
        run: ./COMP36212_EX3_Code/mnist_optimiser.out mnist_data 0.001 0.0001 10 1 2 0.9 0.999 1e-8
